In [1]:
pip list

Package                  Version
------------------------ ------------
absl-py                  1.4.0
annotated-types          0.7.0
anyio                    4.9.0
asttokens                2.2.1
async-timeout            4.0.3
backcall                 0.2.0
cachetools               5.3.1
catboost                 1.2
certifi                  2023.7.22
charset-normalizer       3.2.0
click                    8.1.8
cloudpickle              2.2.1
comm                     0.1.4
contourpy                1.1.0
cycler                   0.11.0
debugpy                  1.6.7.post1
decorator                5.1.1
distro                   1.9.0
exceptiongroup           1.2.2
executing                1.2.0
filelock                 3.15.4
fonttools                4.42.1
fsspec                   2024.6.1
google-auth              2.22.0
google-auth-oauthlib     1.0.0
graphviz                 0.20.1
greenlet                 3.1.1
grpcio                   1.57.0
h11                      0.14.0
h5py        

In [40]:
#one-hot
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# define example
data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot','chill','cool']
values = array(data)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse_output=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[10,:])])
print(argmax(onehot_encoded[0,:]))
print(inverted)

['cold' 'cold' 'warm' 'cold' 'hot' 'hot' 'warm' 'cold' 'warm' 'hot'
 'chill' 'cool']
[1 1 4 1 3 3 4 1 4 3 0 2]
[[0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
1
['chill']


In [45]:
#TF-IDF编码
from sklearn.feature_extraction.text import TfidfVectorizer

# 假设我们有以下三个文本样本
texts = ["apple banana orange", "orange grape", "banana apple"]

# 创建TF-IDF编码器
tfidf_vectorizer = TfidfVectorizer()

# 将文本转换为TF-IDF编码
tfidf_matrix = tfidf_vectorizer.fit_transform(texts)

print(tfidf_matrix.toarray())


[[0.57735027 0.57735027 0.         0.57735027]
 [0.         0.         0.79596054 0.60534851]
 [0.70710678 0.70710678 0.         0.        ]]


In [47]:
pip install gensim

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.5/26.5 MB 6.2 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 1.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.8/82.8 kB 739.2 kB/s eta 0:00:00 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [48]:
from gensim.models import Word2Vec
import numpy as np

# 假设我们有以下三个文本样本
texts = [["apple", "banana", "orange"], ["orange", "grape"], ["banana", "apple"]]

# 训练Word2Vec模型
model = Word2Vec(sentences=texts, vector_size=100, window=5, min_count=1, workers=4)

# 将文本转换为词嵌入表示
embeddings = []
for text in texts:
    embeddings.append(np.mean([model.wv[word] for word in text], axis=0))

print(embeddings)


[array([-3.0204505e-03,  2.3264962e-03,  1.1601960e-03,  4.4585820e-03,
        1.9441830e-03, -1.9793583e-03,  1.2970631e-03,  5.8876574e-03,
       -5.3908695e-03, -1.2438027e-03,  7.7765313e-04, -4.3555088e-03,
       -2.7508973e-04,  4.8439917e-03,  1.9943607e-03, -2.2147025e-04,
        4.9457778e-03,  6.1484794e-03, -6.8439203e-03, -5.0487719e-03,
        8.6510181e-04, -1.4371405e-03,  3.7892871e-03, -5.8771656e-03,
        7.0237126e-03, -1.7782957e-03,  8.4812683e-04,  5.1431102e-03,
       -5.2704127e-03,  2.2443840e-03,  2.6411389e-03, -4.2396737e-03,
        5.1102042e-04, -5.1633450e-03, -2.3695573e-03, -2.4422887e-04,
        4.8550270e-03,  1.1566281e-03,  3.6751798e-03,  1.2127539e-03,
       -2.4331801e-03, -8.3948486e-05, -6.2709409e-03,  6.8203761e-04,
        2.7954980e-04,  4.0425356e-03, -9.6119940e-05,  1.7897417e-03,
        7.0873619e-04,  3.3303697e-03,  3.6556055e-04, -2.5534655e-03,
       -3.8054634e-03, -1.1705247e-03, -5.2071299e-04, -6.7185797e-04,
     